# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export VIRTUALENV_USE_DISTRIBUTE=true
export WORKON_HOME=$HOME/virtualenvs
export PROJECT_HOME=$HOME/workspace
source /usr/local/bin/virtualenvwrapper_lazy.sh

export EDITOR="vim"

# Individual gems for each virtual environment
export GEM_HOME="$VIRTUAL_ENV/gems"
export GEM_PATH=""
export PATH=$PATH:"$GEM_HOME/bin"

# Using in wooky color theme
export HOST_COLOR="cyan"

# TEMP grunt-cli is not avaible somehow
export PATH=$PATH:"/usr/local/share/npm/bin"

# Adding a user-specific $PATH
export PATH="$HOME/.bin":$PATH

# Use GNU version of coreutils by default
export PATH="/usr/local/opt/coreutils/libexec/gnubin":$PATH

alias ls="ls --color"
alias ll="ls -la"

# ZSH tries to expand square brackets (pip install celery[redis])
alias pip="noglob pip"

# Serve current directory by HTTP
function hserve() {
    local host=`hostname`
    local port="${1:-8888}"
    (sleep 1 && open "http://${host}:${port}/")&
    python -m SimpleHTTPServer "$port"
}

ZSH_TMUX_FIXTERM_WITHOUT_256COLOR="screen-256color-s"
ZSH_TMUX_FIXTERM_WITH_256COLOR="screen-256color-s"

bindkey "^o" run-help
bindkey '^?' backward-delete-char   # change ancient backspace behaviour

# Solarized colors for GNU ls and for autocompletion
eval `dircolors $HOME/workspace/dircolors-solarized/dircolors.256dark`
export ZLS_COLORS="${LS_COLORS}"
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31' 
